#! /usr/bin/env bash

set -e

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

version=$(python -c 'import pkg_resources; print(pkg_resources.get_distribution("trustlines-watch").version.replace("+", "_"))')

echo "Tagging with $version"
echo "=====> pushing to dockerhub"

set -x

docker tag watch trustlines/watch:$version
docker push trustlines/watch:$version

docker tag watch trustlines/watch:latest
docker push trustlines/watch:latest
